src/objects/Account_Scheduler_Sort_Field__mdt.object
<CustomObject>
    <description>Defines fields which can be used to sort Accounts on the Account Scheduler page</description>
    <fields>
        <fullName>Default_Sort_Order__c</fullName>
        <label>Default Sort Order</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ascending</fullName>
                    <default>true</default>
                    <label>Ascending</label>
                </value>
                <value>
                    <fullName>Descending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <description>Field to use for sorting</description>
        <inlineHelpText>Field to use for sorting</inlineHelpText>
        <label>Field</label>
        <metadataRelationshipControllingField>Account_Scheduler_Sort_Field__mdt.Object__c</metadataRelationshipControllingField>
        <referenceTo>FieldDefinition</referenceTo>
        <relationshipLabel>Account_Scheduler_Sort_Fields</relationshipLabel>
        <relationshipName>Account_Scheduler_Sort_Fields</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Object containing sort field (currently must be Account)</description>
        <inlineHelpText>Object containing sort field (currently must be Account)</inlineHelpText>
        <label>Object</label>
        <referenceTo>EntityDefinition</referenceTo>
        <relationshipLabel>Account_Scheduler_Sort_Fields</relationshipLabel>
        <relationshipName>Account_Scheduler_Sort_Fields</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Precedence__c</fullName>
        <description>Ordinal value to determine order in which sort fields are displayed in in Account Scheduler</description>
        <inlineHelpText>Ordinal value to determine order in which sort fields are displayed in in Account Scheduler</inlineHelpText>
        <label>Precedence</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Account Scheduler Sort Field</label>
    <pluralLabel>Account Scheduler Sort Fields</pluralLabel>
</CustomObject>

src/classes/CalendarControllerTest.cls
@isTest
private class CalendarControllerTest {

	@isTest static void getLabelsAsJson_returns_serialized_map() {
		CalendarController calendarController = new CalendarController(null);
		String labels = calendarController.getLabelsAsJson();
		System.assert(Pattern.matches('.*"Edit_Event"\\s*:".*', labels),
				'serialized map includes the key "Edit_Event"');
	}

	@isTest static void getLocale_returns_a_locale() {
		CalendarController calendarController = new CalendarController(null);
		String locale = calendarController.getLocale();
		System.assert(Pattern.matches('[a-z][a-z](_[A-Z][A-Z])?', locale),
				'locale string matches the pattern xx_XX');
	}

	@isTest static void getTimezone_returns_a_timezone() {
		CalendarController calendarController = new CalendarController(null);
		String timezone = calendarController.getTimezone();
		System.assert(Pattern.matches('[a-zA-Z_\\-]+/[a-zA-Z_\\-/]+', timezone),
				timezone + ' is a time zone');
	}

	@isTest static void getSortFieldsAsJson_returns_serialized_data() {
		CalendarController calendarController = new CalendarController(null);
		String data = calendarController.getSortFieldsAsJson();
		JSONParser parser = JSON.createParser(data);
		List<Account_Scheduler_Sort_Field__mdt> sortFields =
			new List<Account_Scheduler_Sort_Field__mdt>();
		while (parser.nextToken() != null) {
			if (parser.getCurrentToken() == JSONToken.START_OBJECT) {
				Account_Scheduler_Sort_Field__mdt sortField =
					(Account_Scheduler_Sort_Field__mdt) parser.readValueAsStrict(
							Account_Scheduler_Sort_Field__mdt.class);
				sortFields.add(sortField);
			}
		}
		System.assert(sortFields.size() > 0, 'there is at least one sort field');
		Account_Scheduler_Sort_Field__mdt sortField;
		for (Account_Scheduler_Sort_Field__mdt s : sortFields) {
			if (s.Field__c == 'Account.Name') {
				sortField = s;
			}
		}
		System.assertEquals('Account', sortField.Object__c,
				'object type of sort field');
		System.assertEquals('Account.Name', sortField.Field__c,
				'field referenced by sort field');
		System.assertEquals('Ascending', sortField.Default_Sort_Order__c,
				'default sort order of sort field');
		System.assertEquals('Account Name', sortField.Label,
				'label of sort field');
		System.assertEquals(1.0, sortField.Precedence__c,
				'precedence of sort field');
	}

}